/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deliverable1.landingFrames;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author icani
 */
public class AdminFrame extends javax.swing.JFrame {

    Socket socket;
    PrintWriter outWriter;
    AdminFrame.ClientListener cl;
    ArrayList<JComponent> inputs = new ArrayList();
    Boolean valid;
    int qNum = 0;
    
    public AdminFrame() {
        initComponents();
        valid = false;
        successLabel.setVisible(false);
        timeSuccessLbl.setVisible(false);
        timePanel.setVisible(false);
        searchRespPanel.setVisible(false);
        emailPanel.setVisible(false);
        emailSuccessLbl.setVisible(false);
        
        try{
            socket = new Socket("localhost",32345);
            outWriter = new PrintWriter(socket.getOutputStream());
            cl = new AdminFrame.ClientListener();
            cl.start();
        }catch(IOException e){
            //JOptionPane.showMessageDialog(jPanel1, "Error connecting to Server.");
        }
              
        outWriter.println("/getq,");
        outWriter.flush();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qTypeGroup = new javax.swing.ButtonGroup();
        adminPanel = new javax.swing.JPanel();
        adminWelcomeTxtLabel = new javax.swing.JLabel();
        searchStudRespBtn = new javax.swing.JButton();
        viewResultsBtn = new javax.swing.JButton();
        setOpenCloseBtn = new javax.swing.JButton();
        timePanel = new javax.swing.JPanel();
        openDateField = new javax.swing.JTextField();
        openDateLbl = new javax.swing.JLabel();
        openTimeField = new javax.swing.JTextField();
        closeDateLbl = new javax.swing.JLabel();
        closeDateField = new javax.swing.JTextField();
        closeTimeField = new javax.swing.JTextField();
        sbmtOpClBtn = new javax.swing.JButton();
        timeSuccessLbl = new javax.swing.JLabel();
        qPanel = new javax.swing.JPanel();
        addQSEIBtn = new javax.swing.JButton();
        DisableQBtn = new javax.swing.JButton();
        qListPane = new javax.swing.JScrollPane();
        qListBox = new javax.swing.JList<>();
        successLabel = new javax.swing.JLabel();
        sendEmailBtn = new javax.swing.JButton();
        emailPanel = new javax.swing.JPanel();
        emailChoices = new javax.swing.JComboBox<>();
        emailSelLbl = new javax.swing.JLabel();
        subEmailBtn = new javax.swing.JButton();
        emailSuccessLbl = new javax.swing.JLabel();
        searchRespPanel = new javax.swing.JPanel();
        studNameLbl = new javax.swing.JLabel();
        studNameField = new javax.swing.JTextField();
        searchRespBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminWelcomeTxtLabel.setText("College of Monongalia County SEI System - OFFICIAL ADMINISTRATOR USE ONLY");

        searchStudRespBtn.setText("Search for Student Responses");
        searchStudRespBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudRespBtnActionPerformed(evt);
            }
        });

        viewResultsBtn.setText("View Results");
        viewResultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewResultsBtnActionPerformed(evt);
            }
        });

        setOpenCloseBtn.setText("Set Default Open/Close Time");
        setOpenCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setOpenCloseBtnActionPerformed(evt);
            }
        });

        openDateField.setText("MM/DD/YYYY");

        openDateLbl.setText("Open Date and Time");

        openTimeField.setText("00:00:00 AM/PM");

        closeDateLbl.setText("Close Date and Time");

        closeDateField.setText("MM/DD/YYYY");

        closeTimeField.setText("00:00:00 AM/PM");

        sbmtOpClBtn.setText("Submit");
        sbmtOpClBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmtOpClBtnActionPerformed(evt);
            }
        });

        timeSuccessLbl.setText("Success!");

        javax.swing.GroupLayout timePanelLayout = new javax.swing.GroupLayout(timePanel);
        timePanel.setLayout(timePanelLayout);
        timePanelLayout.setHorizontalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(openDateField)
                        .addComponent(openDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(openTimeField, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(closeDateLbl)
                        .addComponent(closeDateField)
                        .addComponent(closeTimeField))
                    .addGroup(timePanelLayout.createSequentialGroup()
                        .addComponent(sbmtOpClBtn)
                        .addGap(18, 18, 18)
                        .addComponent(timeSuccessLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        timePanelLayout.setVerticalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timePanelLayout.createSequentialGroup()
                .addComponent(openDateLbl)
                .addGap(9, 9, 9)
                .addComponent(openDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeDateLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sbmtOpClBtn)
                    .addComponent(timeSuccessLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addQSEIBtn.setText("Select Questions for SEI");
        addQSEIBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQSEIBtnActionPerformed(evt);
            }
        });

        DisableQBtn.setText("Disable Questions");
        DisableQBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisableQBtnActionPerformed(evt);
            }
        });

        qListPane.setViewportView(qListBox);

        successLabel.setText("Success!");

        javax.swing.GroupLayout qPanelLayout = new javax.swing.GroupLayout(qPanel);
        qPanel.setLayout(qPanelLayout);
        qPanelLayout.setHorizontalGroup(
            qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisableQBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(successLabel)
                .addGap(18, 18, 18)
                .addComponent(addQSEIBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(qListPane)
        );
        qPanelLayout.setVerticalGroup(
            qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qPanelLayout.createSequentialGroup()
                .addComponent(qListPane, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(qPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(qPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DisableQBtn)
                            .addComponent(addQSEIBtn)))
                    .addGroup(qPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(successLabel)))
                .addContainerGap())
        );

        sendEmailBtn.setText("Send Email Reminders");
        sendEmailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEmailBtnActionPerformed(evt);
            }
        });

        emailChoices.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Faculty to Create SEI", "Faculty to View Results", "Students to Complete SEIs" }));
        emailChoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailChoicesActionPerformed(evt);
            }
        });

        emailSelLbl.setText("Select what set of emails to send out.");

        subEmailBtn.setText("Send Email");
        subEmailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subEmailBtnActionPerformed(evt);
            }
        });

        emailSuccessLbl.setText("Success!");

        javax.swing.GroupLayout emailPanelLayout = new javax.swing.GroupLayout(emailPanel);
        emailPanel.setLayout(emailPanelLayout);
        emailPanelLayout.setHorizontalGroup(
            emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailSelLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(emailPanelLayout.createSequentialGroup()
                        .addComponent(subEmailBtn)
                        .addGap(18, 18, 18)
                        .addComponent(emailSuccessLbl))
                    .addComponent(emailChoices, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        emailPanelLayout.setVerticalGroup(
            emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailPanelLayout.createSequentialGroup()
                .addComponent(emailSelLbl)
                .addGap(5, 5, 5)
                .addComponent(emailChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subEmailBtn)
                    .addComponent(emailSuccessLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studNameLbl.setText("Enter Student's Name.");

        studNameField.setText("Student Name");

        searchRespBtn.setText("Search");
        searchRespBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRespBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchRespPanelLayout = new javax.swing.GroupLayout(searchRespPanel);
        searchRespPanel.setLayout(searchRespPanelLayout);
        searchRespPanelLayout.setHorizontalGroup(
            searchRespPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchRespPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchRespPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studNameField)
                    .addGroup(searchRespPanelLayout.createSequentialGroup()
                        .addGroup(searchRespPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studNameLbl)
                            .addComponent(searchRespBtn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchRespPanelLayout.setVerticalGroup(
            searchRespPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchRespPanelLayout.createSequentialGroup()
                .addComponent(studNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchRespBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminWelcomeTxtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(setOpenCloseBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewResultsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchStudRespBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(sendEmailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(searchRespPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(qPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, adminPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(adminWelcomeTxtLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addComponent(searchStudRespBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewResultsBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setOpenCloseBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendEmailBtn))
                            .addComponent(searchRespPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(qPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addQSEIBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQSEIBtnActionPerformed
        // TODO add your handling code here:
        String out = "";
        List<String> list = qListBox.getSelectedValuesList();
        System.err.println(list.size());
        if(list.size() <= 5 && list.size() > 0) {
            System.err.println("Here I am");
            for(String s : list) {
                out += s + ";";
            }
            System.err.println("out addSEI = " + out);
            outWriter.println("/addSEI;" + out);
            outWriter.flush();
        }
    }//GEN-LAST:event_addQSEIBtnActionPerformed

    private void DisableQBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisableQBtnActionPerformed
        // TODO add your handling code here:
        String out = "";
        List<String> indices = qListBox.getSelectedValuesList();
        System.err.println(indices.size());
        if(indices.size() > 0) {
            System.err.println("Here I am in disbable loop");
            for(String s : indices) {
                out += s + ";";
            }
            System.err.println("out disable =" + out);
            outWriter.println("/disableQ;" + out);
            outWriter.flush();
        }
    }//GEN-LAST:event_DisableQBtnActionPerformed

    private void setOpenCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setOpenCloseBtnActionPerformed
        // TODO add your handling code here:
        timePanel.setVisible(true);
    }//GEN-LAST:event_setOpenCloseBtnActionPerformed

    private void sbmtOpClBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmtOpClBtnActionPerformed
        // TODO add your handling code here:
        timeSuccessLbl.setVisible(true);
    }//GEN-LAST:event_sbmtOpClBtnActionPerformed

    private void emailChoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailChoicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailChoicesActionPerformed

    private void sendEmailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEmailBtnActionPerformed
        // TODO add your handling code here:
        emailPanel.setVisible(true);
    }//GEN-LAST:event_sendEmailBtnActionPerformed

    private void subEmailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subEmailBtnActionPerformed
        // TODO add your handling code here:
        emailSuccessLbl.setVisible(true);
    }//GEN-LAST:event_subEmailBtnActionPerformed

    private void searchStudRespBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudRespBtnActionPerformed
        // TODO add your handling code here:
        searchRespPanel.setVisible(true);
    }//GEN-LAST:event_searchStudRespBtnActionPerformed

    private void searchRespBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRespBtnActionPerformed
        // TODO add your handling code here:
        new RawResultsFrame(1).setVisible(true);
    }//GEN-LAST:event_searchRespBtnActionPerformed

    private void viewResultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewResultsBtnActionPerformed
        // TODO add your handling code here:
        new AdminResultsFrame().setVisible(true);
    }//GEN-LAST:event_viewResultsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }
    
    class ClientListener extends Thread{
        
        public void run(){
            try {
                System.out.println("Listener Started");
                BufferedReader inReader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                String inString;
                while((inString = inReader.readLine()) != null){
                    System.err.println("processing command: " + inString);
                    System.out.println(inString);
                    processCommand(inString);

                }   
            } 
            catch(IOException e){
                System.out.println("Error in Client Listener");
            }
        }
        
        public void addToList(String[] str){
            DefaultListModel listmodel = new DefaultListModel();

            try{
                for(int i=1; i<str.length; i++){
                    listmodel.addElement(str[i]);
                }
                qListBox.setModel(listmodel);
                qListBox.setVisible(true);
            }catch(ArrayIndexOutOfBoundsException e){} 
        }
        
        private void processCommand(String inString){
                if(inString.startsWith("/returnQList")) addToList(inString.split(";"));
                else if(inString.startsWith("/retFromSEI")) {
                    addQSEIBtn.setVisible(false);
                    successLabel.setVisible(true);
                    try {
                        TimeUnit.SECONDS.sleep(5); //wait before hiding panel.
                    } catch(InterruptedException e) {} 
                    successLabel.setVisible(false);
                }
                else if(inString.startsWith("/disableQ")) {
                    addToList(inString.split(";"));
                    successLabel.setVisible(true);
                    try {
                        TimeUnit.SECONDS.sleep(5); //wait before hiding panel.
                    } catch(InterruptedException e) {} 
                    successLabel.setVisible(false);
                }

            
        
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DisableQBtn;
    private javax.swing.JButton addQSEIBtn;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JLabel adminWelcomeTxtLabel;
    private javax.swing.JTextField closeDateField;
    private javax.swing.JLabel closeDateLbl;
    private javax.swing.JTextField closeTimeField;
    private javax.swing.JComboBox<String> emailChoices;
    private javax.swing.JPanel emailPanel;
    private javax.swing.JLabel emailSelLbl;
    private javax.swing.JLabel emailSuccessLbl;
    private javax.swing.JTextField openDateField;
    private javax.swing.JLabel openDateLbl;
    private javax.swing.JTextField openTimeField;
    private javax.swing.JList<String> qListBox;
    private javax.swing.JScrollPane qListPane;
    private javax.swing.JPanel qPanel;
    private javax.swing.ButtonGroup qTypeGroup;
    private javax.swing.JButton sbmtOpClBtn;
    private javax.swing.JButton searchRespBtn;
    private javax.swing.JPanel searchRespPanel;
    private javax.swing.JButton searchStudRespBtn;
    private javax.swing.JButton sendEmailBtn;
    private javax.swing.JButton setOpenCloseBtn;
    private javax.swing.JTextField studNameField;
    private javax.swing.JLabel studNameLbl;
    private javax.swing.JButton subEmailBtn;
    private javax.swing.JLabel successLabel;
    private javax.swing.JPanel timePanel;
    private javax.swing.JLabel timeSuccessLbl;
    private javax.swing.JButton viewResultsBtn;
    // End of variables declaration//GEN-END:variables
}
