/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deliverable1.landingFrames;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author icani
 */
public class DeanFrame extends javax.swing.JFrame {

    Socket socket;
    PrintWriter outWriter;
    DeanFrame.ClientListener cl;
    ArrayList<JComponent> inputs = new ArrayList();
    Boolean valid;
    int qNum = 0;
    Boolean noMore = false;
    
    public DeanFrame() {
        initComponents();
        valid = false;
        qListPane.setVisible(false);
        timeSuccessLbl.setVisible(false);
        emailPanel.setVisible(false);
        emailSuccessLbl.setVisible(false);
        timePanel.setVisible(false);
        successLabel.setVisible(false);
        subSelectionBtn.setVisible(false);
        
        try{
            socket = new Socket("localhost",32345);
            outWriter = new PrintWriter(socket.getOutputStream());
            cl = new DeanFrame.ClientListener();
            cl.start();
        }catch(IOException e){
            //JOptionPane.showMessageDialog(jPanel1, "Error connecting to Server.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qTypeGroup = new javax.swing.ButtonGroup();
        adminPanel = new javax.swing.JPanel();
        emailPanel = new javax.swing.JPanel();
        emailChoices = new javax.swing.JComboBox<>();
        emailSelLbl = new javax.swing.JLabel();
        subEmailBtn = new javax.swing.JButton();
        emailSuccessLbl = new javax.swing.JLabel();
        adminWelcomeTxtLabel = new javax.swing.JLabel();
        selectQBtn = new javax.swing.JButton();
        viewResultsBtn = new javax.swing.JButton();
        qListPane = new javax.swing.JScrollPane();
        qListBox = new javax.swing.JList<>();
        subSelectionBtn = new javax.swing.JButton();
        successLabel = new javax.swing.JLabel();
        timePanel = new javax.swing.JPanel();
        openDateField = new javax.swing.JTextField();
        openDateLbl = new javax.swing.JLabel();
        openTimeField = new javax.swing.JTextField();
        closeDateLbl = new javax.swing.JLabel();
        closeDateField = new javax.swing.JTextField();
        closeTimeField = new javax.swing.JTextField();
        sbmtOpClBtn = new javax.swing.JButton();
        timeSuccessLbl = new javax.swing.JLabel();
        setOpenCloseBtn = new javax.swing.JButton();
        sendEmailBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        emailChoices.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Faculty to Create SEI", "Faculty to View Results", "Students to Complete SEIs" }));
        emailChoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailChoicesActionPerformed(evt);
            }
        });

        emailSelLbl.setText("Select what set of emails to send out.");

        subEmailBtn.setText("Send Email");
        subEmailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subEmailBtnActionPerformed(evt);
            }
        });

        emailSuccessLbl.setText("Success!");

        javax.swing.GroupLayout emailPanelLayout = new javax.swing.GroupLayout(emailPanel);
        emailPanel.setLayout(emailPanelLayout);
        emailPanelLayout.setHorizontalGroup(
            emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailSelLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(emailPanelLayout.createSequentialGroup()
                        .addComponent(subEmailBtn)
                        .addGap(18, 18, 18)
                        .addComponent(emailSuccessLbl))
                    .addComponent(emailChoices, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        emailPanelLayout.setVerticalGroup(
            emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailPanelLayout.createSequentialGroup()
                .addComponent(emailSelLbl)
                .addGap(5, 5, 5)
                .addComponent(emailChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subEmailBtn)
                    .addComponent(emailSuccessLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adminWelcomeTxtLabel.setText("College of Monongalia County SEI System - Fine Arts College Dean");

        selectQBtn.setText("Select Questions for SEI");
        selectQBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectQBtnActionPerformed(evt);
            }
        });

        viewResultsBtn.setText("View Results");
        viewResultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewResultsBtnActionPerformed(evt);
            }
        });

        qListPane.setViewportView(qListBox);

        subSelectionBtn.setText("Submit Selected Questions");
        subSelectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subSelectionBtnActionPerformed(evt);
            }
        });

        successLabel.setText("Success!");

        openDateField.setText("MM/DD/YYYY");

        openDateLbl.setText("Open Date and Time");

        openTimeField.setText("00:00:00 AM/PM");

        closeDateLbl.setText("Close Date and Time");

        closeDateField.setText("MM/DD/YYYY");

        closeTimeField.setText("00:00:00 AM/PM");

        sbmtOpClBtn.setText("Submit");
        sbmtOpClBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmtOpClBtnActionPerformed(evt);
            }
        });

        timeSuccessLbl.setText("Success!");

        javax.swing.GroupLayout timePanelLayout = new javax.swing.GroupLayout(timePanel);
        timePanel.setLayout(timePanelLayout);
        timePanelLayout.setHorizontalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(openDateField)
                        .addComponent(openDateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(openTimeField, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(closeDateLbl)
                        .addComponent(closeDateField)
                        .addComponent(closeTimeField))
                    .addGroup(timePanelLayout.createSequentialGroup()
                        .addComponent(sbmtOpClBtn)
                        .addGap(18, 18, 18)
                        .addComponent(timeSuccessLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        timePanelLayout.setVerticalGroup(
            timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timePanelLayout.createSequentialGroup()
                .addComponent(openDateLbl)
                .addGap(9, 9, 9)
                .addComponent(openDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeDateLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(timePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sbmtOpClBtn)
                    .addComponent(timeSuccessLbl)))
        );

        setOpenCloseBtn.setText("Set Default Open/Close Time");
        setOpenCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setOpenCloseBtnActionPerformed(evt);
            }
        });

        sendEmailBtn.setText("Send Email Reminders");
        sendEmailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEmailBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminWelcomeTxtLabel)
                            .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sendEmailBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(setOpenCloseBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selectQBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                .addComponent(viewResultsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qListPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                                .addComponent(successLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subSelectionBtn)))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addComponent(qListPane, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(subSelectionBtn)
                            .addComponent(successLabel)))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addComponent(adminWelcomeTxtLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectQBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewResultsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setOpenCloseBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendEmailBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectQBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectQBtnActionPerformed
        if(!noMore) {
            qListPane.setVisible(true);
            subSelectionBtn.setVisible(true);
            outWriter.println("/getq,");
            outWriter.flush();
        }
    }//GEN-LAST:event_selectQBtnActionPerformed

    private void subSelectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subSelectionBtnActionPerformed
        // TODO add your handling code here:
        String out = "";
        if(qListBox.getSelectedValuesList().size() <= 5 && qListBox.getSelectedValuesList().size() > 0) {
            for(String s : qListBox.getSelectedValuesList()) {
                out += s + ";";
            }
            outWriter.println("/addSEI;" + out);
            outWriter.flush();
        }
      
    }//GEN-LAST:event_subSelectionBtnActionPerformed

    private void sbmtOpClBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmtOpClBtnActionPerformed
        // TODO add your handling code here:
        timeSuccessLbl.setVisible(true);
    }//GEN-LAST:event_sbmtOpClBtnActionPerformed

    private void setOpenCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setOpenCloseBtnActionPerformed
        // TODO add your handling code here:
        timePanel.setVisible(true);
    }//GEN-LAST:event_setOpenCloseBtnActionPerformed

    private void emailChoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailChoicesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailChoicesActionPerformed

    private void subEmailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subEmailBtnActionPerformed
        // TODO add your handling code here:
        emailSuccessLbl.setVisible(true);
    }//GEN-LAST:event_subEmailBtnActionPerformed

    private void sendEmailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEmailBtnActionPerformed
        // TODO add your handling code here:
        emailPanel.setVisible(true);
    }//GEN-LAST:event_sendEmailBtnActionPerformed

    private void viewResultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewResultsBtnActionPerformed
        // TODO add your handling code here:
        new DeanResultsFrame().setVisible(true);
    }//GEN-LAST:event_viewResultsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeanFrame().setVisible(true);
            }
        });
    }
    
    class ClientListener extends Thread{
        
        public void run(){
            try {
                System.out.println("Listener Started");
                BufferedReader inReader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                String inString;
                while((inString = inReader.readLine()) != null){
                    System.err.println("processing command: " + inString);
                    System.out.println(inString);
                    processCommand(inString);

                }   
            } 
            catch(IOException e){
                System.out.println("Error in Client Listener");
            }
        }
        
        public void addToList(String[] str){
            DefaultListModel listmodel = new DefaultListModel();

            try{
                for(int i=1; i<str.length; i++){
                    listmodel.addElement(str[i]);
                }
                qListBox.setModel(listmodel);
                qListBox.setVisible(true);
            }catch(ArrayIndexOutOfBoundsException e){} 
        }
        
        private void processCommand(String inString){
            if(inString.startsWith("/returnQList")) addToList(inString.split(";"));
            else if(inString.startsWith("/retFromSEI")) {
                successLabel.setVisible(true);
                subSelectionBtn.setVisible(false);
                try {
                    TimeUnit.SECONDS.sleep(5); //wait before hiding panel.
                } catch(InterruptedException e) {}
                qListBox.setVisible(false);
                successLabel.setVisible(false);
                qListPane.setVisible(false);
                noMore = true;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminPanel;
    private javax.swing.JLabel adminWelcomeTxtLabel;
    private javax.swing.JTextField closeDateField;
    private javax.swing.JLabel closeDateLbl;
    private javax.swing.JTextField closeTimeField;
    private javax.swing.JComboBox<String> emailChoices;
    private javax.swing.JPanel emailPanel;
    private javax.swing.JLabel emailSelLbl;
    private javax.swing.JLabel emailSuccessLbl;
    private javax.swing.JTextField openDateField;
    private javax.swing.JLabel openDateLbl;
    private javax.swing.JTextField openTimeField;
    private javax.swing.JList<String> qListBox;
    private javax.swing.JScrollPane qListPane;
    private javax.swing.ButtonGroup qTypeGroup;
    private javax.swing.JButton sbmtOpClBtn;
    private javax.swing.JButton selectQBtn;
    private javax.swing.JButton sendEmailBtn;
    private javax.swing.JButton setOpenCloseBtn;
    private javax.swing.JButton subEmailBtn;
    private javax.swing.JButton subSelectionBtn;
    private javax.swing.JLabel successLabel;
    private javax.swing.JPanel timePanel;
    private javax.swing.JLabel timeSuccessLbl;
    private javax.swing.JButton viewResultsBtn;
    // End of variables declaration//GEN-END:variables
}
