/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deliverable1.landingFrames;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author icani
 */
public class FacultyFrame extends javax.swing.JFrame {

    Socket socket;
    PrintWriter outWriter;
    FacultyFrame.ClientListener cl;
    ArrayList<JComponent> inputs = new ArrayList();
    Boolean valid;
    int qNum = 0;
    
    public FacultyFrame() {
        initComponents();
        valid = false;
        successLabel.setVisible(false);
        QPoolPanel.setVisible(false);
        
        try{
            socket = new Socket("localhost",32345);
            outWriter = new PrintWriter(socket.getOutputStream());
            cl = new FacultyFrame.ClientListener();
            cl.start();
        }catch(IOException e){
            //JOptionPane.showMessageDialog(jPanel1, "Error connecting to Server.");
        }
    }
/**
 *
 * @author alexm
 */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qTypeGroup = new javax.swing.ButtonGroup();
        adminPanel = new javax.swing.JPanel();
        adminWelcomeTxtLabel = new javax.swing.JLabel();
        createQBtn = new javax.swing.JButton();
        viewResultsPanel = new javax.swing.JButton();
        QPoolPanel = new javax.swing.JPanel();
        qTxtLabel = new javax.swing.JLabel();
        qTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        scaledRespRadioBtn = new javax.swing.JRadioButton();
        freeRespRadioBtn = new javax.swing.JRadioButton();
        submitQBtn = new javax.swing.JButton();
        successLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminWelcomeTxtLabel.setText("College of Monongalia County SEI System - Faculty View");

        createQBtn.setText("Create Question");
        createQBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createQBtnActionPerformed(evt);
            }
        });

        viewResultsPanel.setText("View Results");

        qTxtLabel.setText("Question Text");

        jLabel1.setText("Question Type");

        qTypeGroup.add(scaledRespRadioBtn);
        scaledRespRadioBtn.setText("Scaled Response");

        qTypeGroup.add(freeRespRadioBtn);
        freeRespRadioBtn.setText("Free Response");

        submitQBtn.setText("Submit");
        submitQBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitQBtnActionPerformed(evt);
            }
        });

        successLabel.setText("Success!");

        javax.swing.GroupLayout QPoolPanelLayout = new javax.swing.GroupLayout(QPoolPanel);
        QPoolPanel.setLayout(QPoolPanelLayout);
        QPoolPanelLayout.setHorizontalGroup(
            QPoolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QPoolPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(QPoolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qTextField)
                    .addGroup(QPoolPanelLayout.createSequentialGroup()
                        .addGroup(QPoolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submitQBtn)
                            .addComponent(scaledRespRadioBtn)
                            .addComponent(jLabel1)
                            .addComponent(qTxtLabel)
                            .addGroup(QPoolPanelLayout.createSequentialGroup()
                                .addComponent(freeRespRadioBtn)
                                .addGap(52, 52, 52)
                                .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 89, Short.MAX_VALUE)))
                .addContainerGap())
        );
        QPoolPanelLayout.setVerticalGroup(
            QPoolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QPoolPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(qTxtLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scaledRespRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QPoolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(freeRespRadioBtn)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QPoolPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(successLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(submitQBtn)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButton1.setText("Select Questions for SEI");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminWelcomeTxtLabel)
                    .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewResultsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createQBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(QPoolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminWelcomeTxtLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createQBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(14, 14, 14)
                .addComponent(viewResultsPanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addComponent(QPoolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createQBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createQBtnActionPerformed
        QPoolPanel.setVisible(true);
    }//GEN-LAST:event_createQBtnActionPerformed

    private void submitQBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitQBtnActionPerformed
        String qType;

        successLabel.setVisible(false);

        if(qTextField.getText() != null) {
            if(freeRespRadioBtn.isSelected()) qType = "free";
            else qType = "scaled";

            outWriter.println("/addq," + qTextField.getText() + "," + qType + "," + qNum);
            outWriter.flush();
            qNum++;
        }
    }//GEN-LAST:event_submitQBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyFrame().setVisible(true);
            }
        });
    }
    
    class ClientListener extends Thread{
        
        public void run(){
            try {
                System.out.println("Listener Started");
                BufferedReader inReader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
                String inString;
                while((inString = inReader.readLine()) != null){
                    System.err.println("processing command: " + inString);
                    System.out.println(inString);
                    processCommand(inString);

                }   
            } 
            catch(IOException e){
                System.out.println("Error in Client Listener");
            }
        }
        
        private void processCommand(String inString){
            String[] stringarr = inString.split(",");
            if(stringarr[0].equals("/addq")) {
                if(stringarr[4].equals("true")) successLabel.setText("SUCCESS");
                else successLabel.setText("FAILURE - TRY AGAIN");
                successLabel.setVisible(true);
            } 
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel QPoolPanel;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JLabel adminWelcomeTxtLabel;
    private javax.swing.JButton createQBtn;
    private javax.swing.JRadioButton freeRespRadioBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField qTextField;
    private javax.swing.JLabel qTxtLabel;
    private javax.swing.ButtonGroup qTypeGroup;
    private javax.swing.JRadioButton scaledRespRadioBtn;
    private javax.swing.JButton submitQBtn;
    private javax.swing.JLabel successLabel;
    private javax.swing.JButton viewResultsPanel;
    // End of variables declaration//GEN-END:variables
}
